# Generated by Django 3.2.6 on 2021-09-21 12:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=10)),
                ('answer_one', models.CharField(choices=[('little', 'Little or none (0% - 50%)'), ('some', 'Some (50% - 75%)'), ('most', 'Most or all (75% - 100%)')], default='Unspecified', max_length=6)),
                ('answer_two', multiselectfield.db.fields.MultiSelectField(choices=[('too-much', 'Too much food.'), ('didnt-like', 'Did not like the food'), ('unknown-prep', 'Did not know how to prepare the food'), ('no-time', 'Did not have time to prepare'), ('not-well', 'Did not feel well enough to prepare myself and no one was available to assist me'), ('went-bad', 'Food went bad before I could eat it'), ('poor-quality', 'Food I received was not the quality I expected'), ('unusual-type', 'Not the types of food my family typically eats')], max_length=84)),
                ('answer_two_a', models.CharField(max_length=256)),
                ('answer_three', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Unspecified', max_length=1)),
                ('answer_three_b', models.TextField(blank=True, null=True)),
                ('answer_four', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Unspecified', max_length=1)),
                ('answer_four_b', models.TextField(blank=True, null=True)),
                ('answer_five', models.CharField(choices=[('5', 'Very satisfied'), ('4', 'Somewhat satisfied'), ('3', 'Neither satisfied or dissatisfied'), ('2', 'Somewhat dissatisfied'), ('1', 'Very dissatisfied')], default='Unspecified', max_length=1)),
                ('answer_six', models.CharField(choices=[('5', 'Very satisfied'), ('4', 'Somewhat satisfied'), ('3', 'Neither satisfied or dissatisfied'), ('2', 'Somewhat dissatisfied'), ('1', 'Very dissatisfied')], default='Unspecified', max_length=1)),
                ('answer_seven', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Unspecified', max_length=1)),
                ('answer_seven_b', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('something-else', 'Preferred to make something else'), ('no-time', 'Did not have time'), ('didnt-like', "Didn't like it"), ('no-time', 'Did not have time to prepare'), ('someone-else-cooks', 'Someone else cooks for me'), ('not-equipt', "Didn't have equipment needed to make the recipe"), ('couldnt-read', "Couldn't read the card"), ('not-well', "Didn't feel well enough to cook"), ('didnt-receive', 'Did not receive a recipe book')], max_length=107, null=True)),
                ('answer_seven_c', models.CharField(blank=True, max_length=256, null=True)),
                ('answer_eight', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('more-recipes', 'More recipes'), ('food-storage-tips', 'Food storage tips'), ('cooking-tips', 'Healthy cooking tips'), ('cooking-class-referrals', 'Referrals to cooking or nutrition classes'), ('other', 'Other food resources like: pantries, drive through food distributions, SNAP application, assistance, 211')], max_length=73, null=True)),
                ('answer_nine', models.TextField()),
            ],
        ),
    ]
