# Generated by Django 3.2.6 on 2021-09-21 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='submission_time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer_nine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='answer_two_a',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
